# Для каждого микросервиса(репозитория) (только на eureka-server добавлять) 
# свой docker-compose(работает аналогично, но собирает только свой микросервис и бд,
# запускаются unit, integration, api тесты) 

services:

  # core-service:
  #   build: .
  #   container_name: meter-service
  #   restart: always
  #   # depends_on:
  #   #   - db
  #   networks:
  #     - backend
      
  #   # environment:
  #   #   # - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tehnomerDB
  #   #   - SPRING_DATASOURCE_USERNAME=tework
  #   #   - SPRING_DATASOURCE_PASSWORD=ksflkOkas23fl9saflKdl349sLfsk1
  #   #   - SPRING_PROFILES_ACTIVE=docker
  #   #   - EUREKA_CLIENT_ENABLED=true 
  #   ports:
  #     - "8070:8070"

  # db:
  #   image: postgres:17
  #   container_name: db
  #   restart: always
  #   networks:
  #     - backend
  #   ports:
  #     - "5434:5432"
  #   environment:
  #     - POSTGRES_DB=tehnomerDB
  #     - POSTGRES_USER=tework
  #     - POSTGRES_PASSWORD=ksflkOkas23fl9saflKdl349sLfsk1
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  kafka-1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx17ESe2esq55je3B6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    # volumes:
    #   - /home/tework/projects/JavaProjects/spring6kafka/kafka_volumes/server-1/:/bitnami/kafka
  kafka-2:
    image: bitnami/kafka:latest
    ports:
      - "10092:10092"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx17ESe2esq55je3B6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:10092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://${HOSTNAME:-localhost}:10092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    # volumes:
    #   - /home/tework/projects/JavaProjects/spring6kafka/kafka_volumes/server-2/:/bitnami/kafka

  kafka-3:
    image: bitnami/kafka:latest
    ports:
      - "11092:11092"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx17ESe2esq55je3B6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:11092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://${HOSTNAME:-localhost}:11092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    # volumes: ework/projects/JavaProjects/spring6kafka/kafka_volumes/server-3/:/bitnami/kafka
    
# networks:
#   backend:

# volumes:
#   postgres_data: