apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: producer-app
          # env:
          #   - name: KAFKA_BOOTSTRAP_SERVERS
          #     value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  ports:
    - port: 8070
  selector:
    app: producer